language: ruby

cache: bundler

rvm:
  - 2.6
  - 2.5
  - 2.4
  - jruby-9.1

branches:
  only:
    - master

install:
  - gem update --system
  - gem install bundler
  - gem install rspec

before_install:
  - bundle install

script:
  - bundle exec rspec --color --require spec_helper
